language: python

python:
  - 3.6.7

services: postgresql

env:
  - DJANGO=2.1.4

before_install:
  - export PYTHONPATH=$HOME/builds/kastrati1/pfe-backend

install:
  - pip3 install django==$DJANGO --quiet
  - pip3 install psycopg2 --quiet
  - pip3 install djangorestframework --quiet
  - pip3 install django-cors-headers --quiet
  - pip3 install djangorestframework-jwt --quiet

script:
  - python3 manage.py test
