language: python
python:
  - 3.6.7
services: postgresql
env:
  - DJANGO=2.1.4
before_install:
  - export PYTHONPATH=$HOME/builds/kastrati1/pfe-backend
install:
  - pip3 install django==$DJANGO --quiet
  - pip3 install psycopg2 --quiet
  - pip3 install djangorestframework --quiet
  - pip3 install django-cors-headers --quiet
  - pip3 install djangorestframework-jwt --quiet
  - pip3 install stripe --quiet
  - pip3 install dj-database-url

script:
  - python3 manage.py test
deploy:
  provider: heroku
  app: myphone-back-dev
  on :
    branch: master
  api_key:
    secure: 5fc53b36-4452-4966-8cbf-39feffcaf316
