# Generated by Django 2.1.3 on 2018-12-10 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=40)),
                ('product_price', models.FloatField(default=0)),
                ('command_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('categorie_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Category')),
            ],
        ),
    ]
