# Generated by Django 2.1.3 on 2018-12-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='description',
        ),
    ]
