# Generated by Django 2.1.4 on 2018-12-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20181206_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='product_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Product'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Categorie'),
        ),
    ]
