# Generated by Django 2.1.4 on 2018-12-07 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20181207_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='command',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
